import './globals.css';
import { Lora } from 'next/font/google';

const lora = Lora({ subsets: ['latin'], variable: '--font-lora' });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>{children}</body>
    </html>
  );
}
